/* eslint-disable */
/**
 * Generated `api` utility.
 *
 * THIS CODE IS AUTOMATICALLY GENERATED.
 *
 * Generated by convex@1.6.3.
 * To regenerate, run `npx convex dev`.
 * @module
 */

import type {
  ApiFromModules,
  FilterApi,
  FunctionReference,
} from "convex/server";
import type * as files from "../files.js";
import type * as passwords from "../passwords.js";
import type * as question from "../question.js";
import type * as quiz from "../quiz.js";
import type * as songs from "../songs.js";
import type * as song_suggest from "../song_suggest.js";
import type * as wishes from "../wishes.js";

/**
 * A utility for referencing Convex functions in your app's API.
 *
 * Usage:
 * ```js
 * const myFunctionReference = api.myModule.myFunction;
 * ```
 */
declare const fullApi: ApiFromModules<{
  files: typeof files;
  passwords: typeof passwords;
  question: typeof question;
  quiz: typeof quiz;
  songs: typeof songs;
  song_suggest: typeof song_suggest;
  wishes: typeof wishes;
}>;
export declare const api: FilterApi<
  typeof fullApi,
  FunctionReference<any, "public">
>;
export declare const internal: FilterApi<
  typeof fullApi,
  FunctionReference<any, "internal">
>;
